import groovy.transform.Field

// We need this because of the mono repo :(
@Field String PROJECT_DIR = 'rusty-report-printer'

pipeline {
    agent {
        kubernetes {
            defaultContainer 'node'
            yaml '''
              spec:
                containers:
                    - name: rusty
                    image: rust:1.58.1
                    command: ["sleep", "infinity"]
                    - name: node
                    image: node:18.11.0-alpine
                    command: ["sleep", "infinity"]

            '''
        }
    }

    options {
        buildDiscarder logRotator(numToKeepStr: '10')
        disableConcurrentBuilds()
        timeout(time: 10, unit: 'MINUTES')
    }

    stages {
        stage('Generate Report') {
            steps {
                dir(PROJECT_DIR) {
                    sh './report_generator.js'
                }
            }
        }

//        stage('Install dependencies') {
//            steps {
//                dir(PROJECT_DIR) {
//                    // if we are on alpine, we need to install musl-dev
//                    // sh 'apk add --no-cache musl-dev=1.2.2-r7'
//                }
//            }
//        }

        stage('Build') {
            container('rusty') {
                steps {
                    dir(PROJECT_DIR) {
                        sh 'cargo build --locked'
                    }
                }
            }
        }

        // Oh no, we can't perform regular Docker Builds on Kubernetes
        /*
        stage('Build Image') {
            environment {
                DOCKER_BUILDKIT = "1"
            }
            steps {
                dir(PROJECT_DIR) {
                    sh 'docker build -t super-report-printer:v0.1.0 .'
                }
            }
        }
         */
    }
}
