import groovy.transform.Field

// We need this because of the mono repo :(
@Field String PROJECT_DIR = 'super-report-printer'

pipeline {
    // We should really use some specific agent, we are getting crashes on some agents without Node or Docker!
    agent {
        kubernetes {
            defaultContainer 'node'
            yaml '''
            spec:
              containers:
                - name: node
                  image: node:16.15-alpine3.16
                  command: ["sleep", "infinity"]
                - name: python
                  image: python:3.10-alpine3.16
                  command: ["sleep", "infinity"]
            '''
        }
    }

    options {
        buildDiscarder logRotator(numToKeepStr: '10')
        disableConcurrentBuilds()
        timeout(time: 10, unit: 'MINUTES')
    }

    stages {
        stage('Generate Report') {
            steps {
                dir(PROJECT_DIR) {
                    container('python') {
                        sh './report_generator.py'
                    }
                }
            }
        }

        stage('Install dependencies') {
            steps {
                dir(PROJECT_DIR) {
                    sh 'npm ci'
                }
            }
        }

        stage('Build Typescript') {
            steps {
                dir(PROJECT_DIR) {
                    sh 'npm run build'
                }
            }
        }

        // stage('Build Image') {
        //     environment {
        //         DOCKER_BUILDKIT = "1"
        //     }
        //     steps {
        //         dir(PROJECT_DIR) {
        //             // Some of our agents don't have Docker, what do we do?
        //             // Also, we are always tagging with the same tag! Help!
        //             sh 'docker build -t super-report-printer:v0.1.0 .'
        //         }
        //     }
        // }
    }
}
